export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';

export const SET_PROPERTY = 'SET_PROPERTY';

export const SET_ITEMS = 'SET_ITEMS';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
export const TOGGLE_ITEM_STATUS = 'TOGGLE_ITEM_STATUS';

export const SET_ORDERS = 'SET_ORDERS';
export const SET_PENDING_ORDERS = 'SET_PENDING_ORDERS';
export const SET_PREPARING_ORDERS = 'SET_PREPARING_ORDERS';
export const SET_DELIVERED_ORDERS = 'SET_DELIVERED_ORDERS';
export const SET_DELIVERING_ORDERS = 'SET_DELIVERING_ORDERS';
export const SET_CANCELLED_ORDERS = 'SET_CANCELLED_ORDERS';
export const CHANGE_ORDER_STATE = 'CHANGE_ORDER_STATE';
export const PUSH_ORDER = 'PUSH_ORDER';


export const SET_REVIEWS ='SET_REVIEWS';
export const RESET_REVIEWS = 'RESET_REVIEWS';

export const SET_TABLES = 'SET_TABLES';

export const SET_ROBOTS = 'SET_ROBOTS';